# Generated by Django 5.2.6 on 2025-09-19 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], default='low', max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_reply_data', models.DateTimeField(help_text='Max reply date')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tickets', to='tickets.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='tickets_tic_categor_3266ff_idx'), models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx')],
            },
        ),
    ]
