# Generated by Django 5.2.6 on 2025-09-20 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, help_text='When this assigment was seen by assignee?', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('solved', 'Solved'), ('impossible', 'Impossible')], default='new', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('assigned_ticket', models.ForeignKey(help_text='Ticket to assign', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
                ('assignee', models.ForeignKey(help_text='User to whom this assignment was assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assigned_ticket', 'assignee'), name='unique_ticket_assignee')],
            },
        ),
    ]
