# Generated by Django 5.2.6 on 2025-09-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
