# Generated by Django 5.2.6 on 2025-09-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_tracking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='max_reply_data',
            new_name='max_reply_date',
        ),
    ]
