# Generated by Django 5.2.6 on 2025-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
