# Generated by Django 5.2.7 on 2025-11-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_age_ticket_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_subject', models.CharField(max_length=1024)),
                ('search_category', models.CharField(max_length=200)),
                ('search_priority', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_logs',
            },
        ),
    ]
