# Generated by Django 5.2.7 on 2026-02-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_role_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlog',
            options={'permissions': [('search_log_export', 'Can export tickets')]},
        ),
    ]
